version: 2.1

jobs:
  build:
    docker:
      - image: cimg/php:8.4
      - image: cimg/postgres:17.0
        environment:
          - POSTGRES_DB=app_dev
          - POSTGRES_USER=api-platform
          - POSTGRES_PASSWORD=!ChangeMe!
    environment:
        APP_ENV: test
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo apt-get install -y libpq-dev

      - restore_cache:
            keys:
                - v1-dependencies-{{ checksum "composer.lock" }}
                # fallback to using the latest cache if no exact match is found
                - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
            key: v1-dependencies-{{ checksum "composer.lock" }}
            paths:
                - ./vendor

      - run: echo 'memory_limit = 2G' >> sudo /usr/local/etc/php/conf.d/docker-php-memlimit.ini
      - run: bin/console cache:warmup --env=dev

      - persist_to_workspace:
          root: .
          paths:
              - .

  test:
    docker:
      - image: cimg/php:8.4
      - image: cimg/postgres:17.0
        environment:
          - POSTGRES_DB=app_dev
          - POSTGRES_USER=api-platform
          - POSTGRES_PASSWORD=!ChangeMe!
    environment:
      APP_ENV: test
    steps:
      - attach_workspace:
          at: .
      - run: composer run phpstan
      - run: bin/console doctrine:schema:validate --skip-sync
      # Confirm migrating all the way down and up works
      - run: php bin/console doctrine:database:create --if-not-exists
      - run: bin/console doctrine:migrations:migrate --no-interaction
      - run: bin/console doctrine:migrations:migrate first --no-interaction
      - run: bin/console doctrine:migrations:migrate --no-interaction

  phpunit:
    docker:
      - image: cimg/php:8.4
      - image: cimg/postgres:17.0
        environment:
          - POSTGRES_DB=app_dev
          - POSTGRES_USER=api-platform
          - POSTGRES_PASSWORD=!ChangeMe!
    environment:
      APP_ENV: test
    steps:
      - attach_workspace:
          at: .
      - run: php bin/console doctrine:database:create --if-not-exists
      - run: bin/console doctrine:migrations:migrate --no-interaction
      - run: php bin/console doctrine:fixtures:load --no-interaction
      - run: composer run phpunit

workflows:
  build-workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - phpunit:
          requires:
            - build
